<a href="https://colab.research.google.com/github/MONISHKA1607/Accelerated_Data_Science_UCS547/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [11]:
#Q1
arr = np.array([1, 2, 3, 6, 4, 5])
print(arr)
print(arr[::-1])

print()


[1 2 3 6 4 5]
[5 4 6 3 2 1]



In [12]:
#Q2
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print(arr1)
print(arr2)
print(arr1 == arr2)

print()

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[ True  True]
 [ True  True]]



In [13]:
#Q3 (i)
x = np.array([1,2,3,4,5,1,2,1,1,1])
print(x)
values, counts = np.unique(x, return_counts=True)
print(values)
print(counts)
max_value = values[counts.argmax()]
print("Most frequent value:", max_value)
indices = np.where(x == max_value)
print("Indices:", indices[0])

print()


[1 2 3 4 5 1 2 1 1 1]
[1 2 3 4 5]
[5 2 1 1 1]
Most frequent value: 1
Indices: [0 5 7 8 9]



In [14]:
#Q3(ii)
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
print(y)
values, counts = np.unique(y, return_counts=True)
print(values)
print(counts)
max_value = values[counts.argmax()]
print("Most frequent value:", max_value)
indices = np.where(y == max_value)
print("Indices:", indices[0])

print()


[1 1 1 2 3 4 2 4 3 3]
[1 2 3 4]
[3 2 3 2]
Most frequent value: 1
Indices: [0 1 2]



In [15]:
# Q4
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(gfg)
print("Sum of all elements:", gfg.sum())
print("Row wise sum:")
print(gfg.sum(axis=1))
print("Column wise sum:")
print(gfg.sum(axis=0))

[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]
Sum of all elements: 45
Row wise sum:
[[14]
 [16]
 [15]]
Column wise sum:
[[20  9 16]]
